
services:
  postgres:
    image: 'postgres:14.3-alpine'
    container_name: 'parser-postgres'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${PARSER_DB_USERNAME}
      - POSTGRES_PASSWORD=${PARSER_DB_PASSWORD}
      - POSTGRES_DB=${PARSER_DB_NAME}
