

#DB
spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5433/${PARSER_DB_NAME}
    username: ${PARSER_DB_USERNAME}
    password: ${PARSER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate.jdbc.timezone: UTC
      hibernate.hibernate.format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml




app:
  base-url: "https://hh.ru/search/vacancy?text="


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}